import esbuild from "esbuild";
import path from "node:path";
import process from "process";
import { polyfillNode } from "esbuild-plugin-polyfill-node";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const fsExtraShimPath = path.resolve("src/shims/fs-extra.ts");
const keyUtilsStubPath = path.resolve("stubs/js-crypto-key-utils/index.js");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	platform: "browser",
	external: [
		"obsidian",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
	],
	plugins: [
		{
			name: "alias-fs-extra-browser-shim",
			setup(build) {
				build.onResolve({ filter: /^fs-extra$/ }, () => ({ path: fsExtraShimPath }));
			},
		},
		{
			name: "alias-js-crypto-key-utils",
			setup(build) {
				build.onResolve({ filter: /^js-crypto-key-utils$/ }, () => ({
					path: keyUtilsStubPath,
				}));
			},
		},
		polyfillNode({
			polyfills: {
				fs: false,
				crypto: true,
				os: true,
				path: true,
				stream: true,
				events: true,
				util: true,
				assert: true,
				constants: true,
				https: true,
				url: true,
				buffer: true,
				process: true,
				http: true,
				vm: true,
				zlib: true,
				string_decoder: true,
				timers: true,
				tls: true,
			},
		}),
	],
	format: "cjs",
	target: "es2018",
	define: {
		"process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
		global: "window",
	},
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
